Add constraints, TypeSchema, and TypeSchemaSubstitutions
cambiata-team/buri-rust pull request #13
Opened 2023-01-20 06:19 UTC by aaronstanek

2023-01-20 15:32 UTC, Nick-Mazuk requested changes

2023-01-20 15:32 UTC, Nick-Mazuk commented on rust/type_checker/src/type_schema_substitutions.rs
> +    disjoint_set: HashMap<GenericTypeId, Option<GenericTypeId>>,
What is the reason for making the value an option?

By default, a `HaspMap` will return an option. So unless there's a specific reason to have `disjoint_set.get(5)` return a `Some(None)`, we can just remove the option.

2023-01-20 15:32 UTC, Nick-Mazuk commented on rust/type_checker/src/type_schema_substitutions.rs
> +    fn get_canonical_id_impl(&mut self, typ: GenericTypeId) -> Option<GenericTypeId> {
It seems like each type constraint will get an ID. However, the same constraint may be given multiple IDs if the constraint was generated in multiple places. So here, you're trying to get the canonical ID for each constraint. That way you can later compare two constraints by simply comparing a number?

Then, are we assigning these IDs consecutively? For instance, the first constraint we find will have an ID of 0, the next 1, and so on?

If so, consider using a vector here. It'll be faster and the code will be simpler. And it's more intuitive to check if the ID exists—is it smaller than the length of the vector?

```rust
pub struct TypeSchemaSubstitutions {
    ids: Vec<GenericTypeId>,
}
```

If you do this, then `insert_new_id` would probably instead be the following:

```rust
pub fn get_new_id(&mut self) -> GenericTypeId {
    let id = self.ids.len();
    self.ids.push(id);
    id
}
```

Then by default, `self.ids[id]` will always return the canonical ID for `id`. No need to check if it has a parent or not. If you need to merge two IDs, then you can just overwrite one of them (which you're doing anyways).

The disadvantage of this approach is you'll essentially have a single object that can assign IDs, which means you cannot multithread that process. But I think multithreading is out of the scope for both the MVP and bootstrapped parser (JS can't really multithread, anyways).

2023-01-20 15:32 UTC, Nick-Mazuk commented on rust/type_checker/src/type_schema_substitutions.rs
> +        for (_, constraint_vec) in new_schema.constraints {
No logic in tests. That includes for loops.

Just write out each of the asserts for the values you want to test individually.

2023-01-20 15:32 UTC, Nick-Mazuk commented on rust/type_checker/src/type_schema.rs
> +        self.next_id += 1;
Correct me if I'm wrong, but it seems like if you're doing it this way, then we may end up with duplicate constraint IDs across the program. Wouldn't that provide the opportunity to have two different constraints get the same ID and create many bugs? If so, that's also a security concern because someone could exploit it.

2023-01-20 16:31 UTC, aaronstanek commented on rust/type_checker/src/type_schema_substitutions.rs
> +    disjoint_set: HashMap<GenericTypeId, Option<GenericTypeId>>,
If a key maps to None, it means that the key is its own canonical id. If a key maps to Some, then the payload of Some is a better guess for the canonical id than the key. I'll add a comment explaining this.

2023-01-20 16:48 UTC, aaronstanek commented on rust/type_checker/src/type_schema_substitutions.rs
> +    fn get_canonical_id_impl(&mut self, typ: GenericTypeId) -> Option<GenericTypeId> {
I'll add some comments explaining all of this.

The ids refer to types, not constraints.

In the current implementation, type ids are be inserted consecutively, in increasing order, starting from zero. In this case, a vector would be substantially more performant than a HashMap. But if the implementation were to ever change in the future, then a vector might create issues.

Thinking about this, it is probably safe to use a vector here, and the performance benefits would be substantial. I'm going to make that change and add a test requiring that ids be inserted consecutively, in increasing order, starting from zero.

2023-01-20 16:52 UTC, aaronstanek commented on rust/type_checker/src/type_schema_substitutions.rs
> +        for (_, constraint_vec) in new_schema.constraints {
The issue that I ran into is that I wanted to assert that the constraint vectors of `type_a` and the `type_b` are concatenated and placed under a single key. Whether the final key is `type_a` or `type_b` is an implementation detail, and should not appear in the tests.

If you have a cool trick for doing this without logic or arithmetic that would be really handy.

2023-01-20 16:53 UTC, aaronstanek commented on rust/type_checker/src/type_schema.rs
> +        self.next_id += 1;
The ids refer to types, not constraints.

The ids are scoped to the level of a function definition, record definitions, or tag union.

I'll add some comments explaining this.

2023-01-21 16:16 UTC, Nick-Mazuk commented on rust/type_checker/src/type_schema_substitutions.rs
> +    disjoint_set: HashMap<GenericTypeId, Option<GenericTypeId>>,
What if the value is just always the canonical ID? If a key maps to itself, then you know it's its own canonical ID. If it maps to something else, then you know that is it's canonical ID.

This makes looking up a canonical ID much simpler. Just lookup the value associated with that key.

2023-01-21 16:18 UTC, Nick-Mazuk commented on rust/type_checker/src/type_schema_substitutions.rs
> +    fn get_canonical_id_impl(&mut self, typ: GenericTypeId) -> Option<GenericTypeId> {
In general, as long as the API doesn't change, it gives you the flexibility to change the underlying data structures in the future without much issue.

2023-01-21 18:47 UTC, aaronstanek commented on rust/type_checker/src/type_schema_substitutions.rs
> +    disjoint_set: HashMap<GenericTypeId, Option<GenericTypeId>>,
The current implementation has amortized `O(1)`* time lookup and updates. The changes you propose would guarantee a non-amortized `O(1)` lookup time, but would slow updates to `O(n)`, where `n` is the number of types in the schema.

I think that it is important to clarify that when type `a` is set equal to type `b`, all other types equal to `a` must then be made equal to all other types equal to `b`. The [disjoint set data structure](https://en.wikipedia.org/wiki/Disjoint-set_data_structure) is designed for exactly this situation.

*Disjoint sets aren't exactly `O(1)` time. The data structure has a rather complicated time complexity, but from an engineering standpoint the distinction between `O(1)` and very nearly `O(1)` is meaningless.

2023-01-21 19:04 UTC, Nick-Mazuk commented on rust/type_checker/src/type_schema_substitutions.rs
> +    disjoint_set: HashMap<GenericTypeId, Option<GenericTypeId>>,
You can still use disjoint sets the way I'm proposing. It's actually the main way I've implemented them in the past.

The main difference is that you'll have a simpler data structure, the code will be simpler, and it'll take up less memory.

```rust
#[derive(Default)]
pub struct TypeSchemaSubstitutions {
    ids: Vec<GenericTypeId>,
}

impl TypeSchemaSubstitutions {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn get_new_id(&mut self) -> GenericTypeId {
        let id = self.ids.len();
        self.ids.push(id);
        id
    }

    pub fn get_canonical_id(&mut self, typ: GenericTypeId) -> GenericTypeId {
        let parent = self.ids[typ];
        if parent == typ {
            return typ;
        }
        self.ids[typ] = self.ids[parent];
        self.ids[typ]
    }
}
```

2023-01-21 20:25 UTC, aaronstanek commented on rust/type_checker/src/type_schema_substitutions.rs
> +    disjoint_set: HashMap<GenericTypeId, Option<GenericTypeId>>,
I was getting tripped up by the terminology. In a union find / disjoint set data structure, each entry is mapped to a parent element, not a canonical element (Wikipedia uses "root" instead of "canonical"). But I do understand now what you mean by removing the option. I included to be more Rust-idiomatic, but on reconsidering, I'm not sure that it makes much of a difference. I'll remove it.

2023-01-21 23:28 UTC, Nick-Mazuk commented on rust/type_checker/src/type_schema_substitutions.rs
> +        for (_, constraint_vec) in new_schema.constraints {
Hmm…

I've thought of several ways to do this, but all of those would make the code more confusing.

If you needed to verify _every single constraint_, this loop might be the cleanest option unfortunately.

However, if you did not need to very every single constraint, I'd just pick the first elements from every item.

```rust
if let Constraint::HasField(field_constraint) = new_schema.constraints[0].1[0] {
    assert_eq!(
        substitutions.get_canonical_id(field_constraint.field_type),
        substitutions.get_canonical_id(type_a)
    );
}
```

One other thing, you've also already set `type_a` to equal `type_b` above.

```rust
substitutions.set_types_equal(type_a, type_b);
```

So checking the constraints equal both types is redundant. You can trust the `set_types_equal` method because you already wrote tests for that.

2023-01-22 17:34 UTC, Nick-Mazuk approved these changes
Approving since I think we're aligned on the fixes. That way you're unblocked from merging once it's ready.

2023-01-22 21:37 UTC, aaronstanek commented
/aviator merge

2023-01-22 21:38 UTC, merged