Add Buri JS Lite
cambiata-team/buri-rust pull request #253
Opened 2023-03-14 00:22 UTC by aaronstanek

2023-03-14 00:48 UTC, Nick-Mazuk requested changes
Minor comments. I'd happily approve this once those are addressed. If you feel like they're bad ideas, feel free to just resolve them.

I like how simple you made this code. Very straight-forward and easy to follow in my opinion.

2023-03-14 00:48 UTC, Nick-Mazuk commented on rust/buri_js_lite/src/lib.rs
> +    stringify_path(source_path.with_extension("mjs").as_path())
Could we output to the `/.buri/dist` folder like the e2e tests currently do? That way the compiled JS outputs aren't saved into the repository.

I assume that we'll eventually write JS tests for the compiled outputs. If so, we'll want to keep those and ignore the other JS files.

Alternatively if you want to keep the compiled outputs next to the Buri source files, could we add `*.mjs` to the `.gitignore` file?

2023-03-14 00:48 UTC, Nick-Mazuk commented on README.md
> +This project contains an example compiler for Buri called "Buri JS Lite". Currently this compiler can only compile to JavaScript, and can only compile Buri programs consisting of a single source file
Nit: Out of curiosity, any reason why it's specifically called "Lite"? Is it because it can only do single-file compilation?

My preference is that we remove the "Lite" part from the name. That way when we get multi-file compilation working, we won't need to update the CI tests and anywhere else this compiler is used. We'll only need to update the README to remove the caveat that it only works for single-file programs.

2023-03-14 16:49 UTC, aaronstanek commented on README.md
> +This project contains an example compiler for Buri called "Buri JS Lite". Currently this compiler can only compile to JavaScript, and can only compile Buri programs consisting of a single source file
I was actually thinking to include the "lite" because its the reference implementation. I'd like to reverrse the term "Buri JS compiler" for the fully-featured compiler written in Buri, although we could probably come up with a better name.

2023-03-14 16:50 UTC, aaronstanek commented on rust/buri_js_lite/src/lib.rs
> +    stringify_path(source_path.with_extension("mjs").as_path())
That's a good point. I'll make the fix.

2023-03-15 05:43 UTC, Nick-Mazuk commented on README.md
> +This project contains an example compiler for Buri called "Buri JS Lite". Currently this compiler can only compile to JavaScript, and can only compile Buri programs consisting of a single source file
Makes sense. Let's keep it, then.

2023-03-15 05:44 UTC, Nick-Mazuk approved these changes

2023-03-15 18:10 UTC, aaronstanek commented
/aviator merge

2023-03-15 18:10 UTC, merged