Add codePointAt method to Buri string type
cambiata-team/buri-rust pull request #274
Opened 2023-03-21 23:45 UTC by aaronstanek

2023-03-22 04:31 UTC, Nick-Mazuk requested changes
Just want to ensure any methods we add are well thought-out since they will be difficult (though not impossible) to change later.

2023-03-22 04:31 UTC, Nick-Mazuk commented on packages/std/prelude/string.js
> +    codePointAt(index) {
I'm not sure if this name is self explanatory. Would `charAt` be appropriate? Or even `get` to make the API consistent with lists?

2023-03-22 04:31 UTC, Nick-Mazuk commented on rust/type_checker/types/src/default_types.rs
> +            Method {
Yes, add this here. However note that it'll cause a lot of tests in the [parsed_expression_to_generic_expression.rs](https://github.com/cambiata-team/buri/blob/main/rust/type_checker/translator/src/parsed_expression_to_generic_expression.rs) because it's adding new constraints. So any test that hardcodes the number of constraints that involves strings will need to be updated as well.

2023-03-22 04:31 UTC, Nick-Mazuk commented on tests/js/valid/strings/codePointAt.test.js
> +it("\"hello\":codePointAt(-1) == #none", () => {
It may be nice for the API to wrap around, so `-1` retrieves the last element, `-2` the second-to-last, etc.

JavaScript's `at` method is a good example of this. And I believe Python does something similar.

If we do this, then `|index| >= self.length` would return `#none`.

2023-03-22 20:40 UTC, aaronstanek commented on packages/std/prelude/string.js
> +    codePointAt(index) {
I agree that the permanence of the names of built-in functions warrants a higher degree of thought and scrutiny. For this reason, I encourage the most challenging feedback you can provide.

Just so we are on the same page, this method returns the nth Unicode scalar value in a string. It's return type is `Int`. The behavior of this method is distinct from getting the nth character in a string, which in Buri would have a return type of `Str`.

The decision criteria which resulted in me selecting `codePointAt` were the following:
1. The name must be concise and descriptive.
2. The name must not be confused for a method that returns the nth character of a string.
3. The name must not be confused for a method that converts a string to a list of Unicode scalar values.
4. If possible, the name should be similar to equivalent methods in other languages.

I think that your suggestions of `charAt` and `get` would be really good for a method that returns the nth character of a string. However, these suggestions don't work too well with my second criterion. I like the idea of having API consistency between lists and strings, and I think it would be a great idea to have a `get` method on strings that returns the nth character.

Aside from that, the fact that you find `codePointAt` less than self-explanatory is a pretty big blow to it's candidacy under my first criterion. I'll probably go back to the drawing board here.

The reasons why I liked `codePointAt` were the following:
- It was relatively short
- I found it self-descriptive
- I figured that by using the term "code point" it was unlikely to be confused for a method that returns a character
- I figured that by using the term "at" it was unlikely to be confused for a method that converts a string to a list of Unicode scalar values
- Both Java and JavaScript call their equivalent to this method `codePointAt`

What I didn't like about the name `codePointAt` is that it implies that it returns a Unicode code point, when in actuality it returns a Unicode scalar value. The distinction between these two terms is small, but it may be important in some niche edge cases.

2023-03-22 20:43 UTC, aaronstanek commented on rust/type_checker/types/src/default_types.rs
> +            Method {
Thanks for the heads-up.

2023-03-22 20:43 UTC, aaronstanek commented on tests/js/valid/strings/codePointAt.test.js
> +it("\"hello\":codePointAt(-1) == #none", () => {
I agree, this is a good behavior.

2023-03-22 20:48 UTC, aaronstanek commented on packages/std/prelude/string.js
> +    codePointAt(index) {
I am also considering:
- `codeAt`
- `charCodeAt`
- `valueAt`
- `unicodeAt`

2023-03-22 23:31 UTC, aaronstanek commented on tests/js/valid/strings/codePointAt.test.js
> +it("\"hello\":codePointAt(-1) == #none", () => {
Implemented.

2023-03-22 23:31 UTC, aaronstanek commented on rust/type_checker/types/src/default_types.rs
> +            Method {
Fixed.

2023-03-23 14:12 UTC, Nick-Mazuk commented on packages/std/prelude/string.js
> +    codePointAt(index) {
Oh, I misinterpreted the purpose of this function.

Of these, I'd suggest `getCharCode`. `CarCode` because that's what JS calls it. `get` to make it similar to lists.

So…

- Str
  - get() – get's the nth character
  - getCharCode() - get's the nth character code
- List
  - get() - get's the nth item

2023-03-23 19:01 UTC, aaronstanek commented on packages/std/prelude/string.js
> +    codePointAt(index) {
I like this.

2023-03-23 19:38 UTC, aaronstanek commented on packages/std/prelude/string.js
> +    codePointAt(index) {
Name changed.

2023-03-24 16:37 UTC, Nick-Mazuk requested changes

2023-03-24 16:37 UTC, Nick-Mazuk commented on packages/std/prelude/string.js
> +    jsIndexForNthCharacter(n) {
Could we move this out of the class? That way if someone does add the trait method `jsIndexForNthCharacter` to a `Str`, this won't be overwritten. It'll also make things (slightly) faster because it's one fewer method lookup.

2023-03-24 16:37 UTC, Nick-Mazuk commented on packages/std/prelude/string.js
> +        if (n >= 0) {
Both branches are almost exactly identical. Consider refactoring this to remove the if statement.

```js
let parity = n >= this.length ? 1 : -1
// ...
characterIndex += parity
jsIndex += (1 + ((this.charCodeAt(jsIndex) & 0xF800) === 0xD800)) * parity
```

2023-03-24 16:37 UTC, Nick-Mazuk commented on packages/std/prelude/string.js
> +            while (true) {
`while (true)` is almost always a code smell. Consider refactoring this:

```js
while (Math.abs(jsIndex) < this.length) {
    // ...
}
```

2023-03-24 16:37 UTC, Nick-Mazuk commented on packages/std/prelude/string.js
> +        // ((this.charCodeAt(jsIndex) & 0xF800) === 0xD800) is true if and only if the code point at jsIndex is a UTF-16 surrogate.
Instead of explaining this in a comment, consider moving this into it's own function. That removes duplication and allows the code itself to explain itself.

```js
// this should probably even go outside the class
const isUtf16Surrogate = (charCode) => (charCode & 0xF800) === 0xD800

// when it's used
isUtf16Surrogate(this.charCodeAt(jsIndex))
```

2023-03-24 16:37 UTC, Nick-Mazuk commented on packages/std/prelude/string.js
> +                    jsIndex += 1 + ((this.charCodeAt(jsIndex) & 0xF800) === 0xD800)
It's generally not a good idea to rely on type coercion since it makes code harder to read (especially when it's implicit coercion like it is here).

2023-03-24 16:37 UTC, Nick-Mazuk commented on packages/std/prelude/string.js
> +        else {
Nit: else should be on the same line as the previous curly brace: `} else {`

2023-03-24 16:37 UTC, Nick-Mazuk commented on packages/std/prelude/string.js
> +    /// Assume that the string is valid UTF-16.
If you want to add doc comments to JS code, use JSDoc comments. This is not only the industry standard, but it's also how you get intellisense in VS Code.

```js
/**
 * Assume the string is valid UTF-16.
 * ...
 */
jsIndexForNthCharacter(n) {
```

2023-03-26 20:16 UTC, Nick-Mazuk requested changes
After this, LGTM.

2023-03-26 20:16 UTC, Nick-Mazuk commented on packages/std/prelude/string.js
> +        else {
Hmm… looks like this is still unresolved.

2023-03-26 20:16 UTC, Nick-Mazuk commented on packages/std/prelude/string.js
> +const jsIndexForNthCharacter = (string, n) => {
Definitely much better and easier to read! Two things, though:

- Use ternary operators to eliminate uninitialized values.
- Remove else blocks after return statements to remove unnecessary nesting.

```js
let step = n >= 0 ? 1 : -1
let characterIndex = n >= 0 ? 0 : 1
let jsIndex = n >= 0 ? 0 : string.length - 1

while (jsIndex >= 0 && jsIndex < string.length) {
    if (characterIndex === n) {
        if (step === -1 && isUtf16SurrogateAtIndex(string, jsIndex)) {
            return jsIndex - 1
        }
        return jsIndex
    }

    characterIndex += step
    if (isUtf16SurrogateAtIndex(string, jsIndex)) {
        jsIndex += step * 2
    } else {
        jsIndex += step
    }
}

return -1
```

2023-03-27 14:28 UTC, Nick-Mazuk approved these changes

2023-03-27 14:28 UTC, Nick-Mazuk commented on packages/std/prelude/string.js
> +        } else {
You still don't need this else here since all paths of the if statement `return`.

2023-03-27 14:30 UTC, closed without merging